language: python
python:
  - "3.7-dev"
services:
  - postgresql
install:
  - pip install -r backend/requirements_test.txt
env:
  - DATABASE_URL=postgres://postgres@localhost/testscoring
    ENVIRON=local
    DJANGO_SETTINGS_MODULE=api.settings.local
before_script:
  - cd backend
  - psql -c 'create database testscoring;' -U postgres
  - python manage.py migrate
script:
  - pytest
